### ISSUE TITLE
[blocker] Fix Camera Crash

### ISSUE THREAD

**Issue by claucookie** [CoVital-Project/HealthWatcher#2]
**Issue:**
The camera is nor working due to lack of permissions to run.

**Description:**
When opening any of the screens to measure heart rate or oxigen the app crashes.

**Stacktrace:**
```
 Process: com.example.yo7a.healthwatcher, PID: 15947
    java.lang.RuntimeException: Unable to resume activity {com.example.yo7a.healthwatcher/com.example.yo7a.healthwatcher.HeartRateProcess}: java.lang.RuntimeException: Fail to connect to camera service
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:495)
        at android.hardware.Camera.open(Camera.java:356)
        at com.example.yo7a.healthwatcher.HeartRateProcess.onResume(HeartRateProcess.java:104)
```

**Potential issue:**
It might be caused by the lack of requesting camera permissions.

For more information about requesting permissions:
https://developer.android.com/training/permissions/requesting

**Comment by Ian2020** [comment]
Again somebody else may have attempted to fixed this already (untested): https://github.com/latinosamuel/HealthWatcher/commit/cbbf633243d537f464138478002dc0414a993105

**Comment by claucookie** [comment]
We are not gonna use this project since is very old, we will implement the camera capabilities on another app and will extract the algorithm from here.
